FROM apache/airflow:2.10.5-python3.12

RUN pip install --no-cache-dir \
    "apache-airflow-providers-apache-kafka" \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.12.txt"
